dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull ethereum/client-go:v1.8.6

env:
  - NETWORK=ganache
  - NETWORK=geth
  - NETWORK=coverage

matrix:
  allow_failures:
    - env: NETWORK=coverage
    - env: NETWORK=geth

install:
  - npm install

script:
  - npm run ci
