dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull ethereum/client-go:latest
  - docker pull ethereum/solc:0.4.24

env:
  - NETWORK=ganache
  - NETWORK=geth
  - NETWORK=coverage
  - NETWORK=ganache GAS_REPORTER=true

matrix:
  fast_finish: true
  allow_failures:
    - env: NETWORK=coverage
    - env: NETWORK=geth
    - env: NETWORK=ganache GAS_REPORTER=true

install:
  - npm install

script:
  - npm run ci
