dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker pull ethereum/client-go:1.8.6

env:
  - NETWORK=GANACHE
  - NETWORK=GETH
  - NETWORK=COVERAGE

matrix:
  allow_failures:
    - env: NETWORK=COVERAGE

install:
  - npm install

script:
  - npm run ci
